services:
  - type: web
    name: techadvise-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://techadvise-jvsc.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
