services:
  # Backend API Service
  - type: web
    name: techadvise-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Frontend Service (Optional - if you want separate frontend deployment)
  - type: web
    name: techadvise-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://techadvise-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
