services:
  - type: web
    name: techadvise-backend
    env: node
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://techadvise.in
      - key: API_RATE_LIMIT
        value: 100
      - key: API_RATE_WINDOW
        value: 900000
      - key: JWT_EXPIRES_IN
        value: 7d

staticSites:
  - type: static
    name: techadvise-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
